use sdl2::keyboard::Keycode;

#[allow(dead_code)]
pub(super) fn key_to_keycode(key: usize) -> Option<Keycode> {
    KEYS.get(key).cloned()
}

pub(super) fn keycode_to_key(keycode: Keycode) -> usize {
    (match keycode {
        Keycode::Backspace => Key::Backspace,
        Keycode::Tab => Key::Tab,
        Keycode::Return => Key::Return,
        Keycode::Escape => Key::Escape,
        Keycode::Space => Key::Space,
        Keycode::Exclaim => Key::Exclaim,
        Keycode::Quotedbl => Key::Quotedbl,
        Keycode::Hash => Key::Hash,
        Keycode::Dollar => Key::Dollar,
        Keycode::Percent => Key::Percent,
        Keycode::Ampersand => Key::Ampersand,
        Keycode::Quote => Key::Quote,
        Keycode::LeftParen => Key::LeftParen,
        Keycode::RightParen => Key::RightParen,
        Keycode::Asterisk => Key::Asterisk,
        Keycode::Plus => Key::Plus,
        Keycode::Comma => Key::Comma,
        Keycode::Minus => Key::Minus,
        Keycode::Period => Key::Period,
        Keycode::Slash => Key::Slash,
        Keycode::Num0 => Key::Num0,
        Keycode::Num1 => Key::Num1,
        Keycode::Num2 => Key::Num2,
        Keycode::Num3 => Key::Num3,
        Keycode::Num4 => Key::Num4,
        Keycode::Num5 => Key::Num5,
        Keycode::Num6 => Key::Num6,
        Keycode::Num7 => Key::Num7,
        Keycode::Num8 => Key::Num8,
        Keycode::Num9 => Key::Num9,
        Keycode::Colon => Key::Colon,
        Keycode::Semicolon => Key::Semicolon,
        Keycode::Less => Key::Less,
        Keycode::Equals => Key::Equals,
        Keycode::Greater => Key::Greater,
        Keycode::Question => Key::Question,
        Keycode::At => Key::At,
        Keycode::LeftBracket => Key::LeftBracket,
        Keycode::Backslash => Key::Backslash,
        Keycode::RightBracket => Key::RightBracket,
        Keycode::Caret => Key::Caret,
        Keycode::Underscore => Key::Underscore,
        Keycode::Backquote => Key::Backquote,
        Keycode::A => Key::A,
        Keycode::B => Key::B,
        Keycode::C => Key::C,
        Keycode::D => Key::D,
        Keycode::E => Key::E,
        Keycode::F => Key::F,
        Keycode::G => Key::G,
        Keycode::H => Key::H,
        Keycode::I => Key::I,
        Keycode::J => Key::J,
        Keycode::K => Key::K,
        Keycode::L => Key::L,
        Keycode::M => Key::M,
        Keycode::N => Key::N,
        Keycode::O => Key::O,
        Keycode::P => Key::P,
        Keycode::Q => Key::Q,
        Keycode::R => Key::R,
        Keycode::S => Key::S,
        Keycode::T => Key::T,
        Keycode::U => Key::U,
        Keycode::V => Key::V,
        Keycode::W => Key::W,
        Keycode::X => Key::X,
        Keycode::Y => Key::Y,
        Keycode::Z => Key::Z,
        Keycode::Delete => Key::Delete,
        Keycode::CapsLock => Key::CapsLock,
        Keycode::F1 => Key::F1,
        Keycode::F2 => Key::F2,
        Keycode::F3 => Key::F3,
        Keycode::F4 => Key::F4,
        Keycode::F5 => Key::F5,
        Keycode::F6 => Key::F6,
        Keycode::F7 => Key::F7,
        Keycode::F8 => Key::F8,
        Keycode::F9 => Key::F9,
        Keycode::F10 => Key::F10,
        Keycode::F11 => Key::F11,
        Keycode::F12 => Key::F12,
        Keycode::PrintScreen => Key::PrintScreen,
        Keycode::ScrollLock => Key::ScrollLock,
        Keycode::Pause => Key::Pause,
        Keycode::Insert => Key::Insert,
        Keycode::Home => Key::Home,
        Keycode::PageUp => Key::PageUp,
        Keycode::End => Key::End,
        Keycode::PageDown => Key::PageDown,
        Keycode::Right => Key::Right,
        Keycode::Left => Key::Left,
        Keycode::Down => Key::Down,
        Keycode::Up => Key::Up,
        Keycode::NumLockClear => Key::NumLockClear,
        Keycode::KpDivide => Key::KpDivide,
        Keycode::KpMultiply => Key::KpMultiply,
        Keycode::KpMinus => Key::KpMinus,
        Keycode::KpPlus => Key::KpPlus,
        Keycode::KpEnter => Key::KpEnter,
        Keycode::Kp1 => Key::Kp1,
        Keycode::Kp2 => Key::Kp2,
        Keycode::Kp3 => Key::Kp3,
        Keycode::Kp4 => Key::Kp4,
        Keycode::Kp5 => Key::Kp5,
        Keycode::Kp6 => Key::Kp6,
        Keycode::Kp7 => Key::Kp7,
        Keycode::Kp8 => Key::Kp8,
        Keycode::Kp9 => Key::Kp9,
        Keycode::Kp0 => Key::Kp0,
        Keycode::KpPeriod => Key::KpPeriod,
        Keycode::Application => Key::Application,
        Keycode::Power => Key::Power,
        Keycode::KpEquals => Key::KpEquals,
        Keycode::F13 => Key::F13,
        Keycode::F14 => Key::F14,
        Keycode::F15 => Key::F15,
        Keycode::F16 => Key::F16,
        Keycode::F17 => Key::F17,
        Keycode::F18 => Key::F18,
        Keycode::F19 => Key::F19,
        Keycode::F20 => Key::F20,
        Keycode::F21 => Key::F21,
        Keycode::F22 => Key::F22,
        Keycode::F23 => Key::F23,
        Keycode::F24 => Key::F24,
        Keycode::Execute => Key::Execute,
        Keycode::Help => Key::Help,
        Keycode::Menu => Key::Menu,
        Keycode::Select => Key::Select,
        Keycode::Stop => Key::Stop,
        Keycode::Again => Key::Again,
        Keycode::Undo => Key::Undo,
        Keycode::Cut => Key::Cut,
        Keycode::Copy => Key::Copy,
        Keycode::Paste => Key::Paste,
        Keycode::Find => Key::Find,
        Keycode::Mute => Key::Mute,
        Keycode::VolumeUp => Key::VolumeUp,
        Keycode::VolumeDown => Key::VolumeDown,
        Keycode::KpComma => Key::KpComma,
        Keycode::KpEqualsAS400 => Key::KpEqualsAS400,
        Keycode::AltErase => Key::AltErase,
        Keycode::Sysreq => Key::Sysreq,
        Keycode::Cancel => Key::Cancel,
        Keycode::Clear => Key::Clear,
        Keycode::Prior => Key::Prior,
        Keycode::Return2 => Key::Return2,
        Keycode::Separator => Key::Separator,
        Keycode::Out => Key::Out,
        Keycode::Oper => Key::Oper,
        Keycode::ClearAgain => Key::ClearAgain,
        Keycode::CrSel => Key::CrSel,
        Keycode::ExSel => Key::ExSel,
        Keycode::Kp00 => Key::Kp00,
        Keycode::Kp000 => Key::Kp000,
        Keycode::ThousandsSeparator => Key::ThousandsSeparator,
        Keycode::DecimalSeparator => Key::DecimalSeparator,
        Keycode::CurrencyUnit => Key::CurrencyUnit,
        Keycode::CurrencySubUnit => Key::CurrencySubUnit,
        Keycode::KpLeftParen => Key::KpLeftParen,
        Keycode::KpRightParen => Key::KpRightParen,
        Keycode::KpLeftBrace => Key::KpLeftBrace,
        Keycode::KpRightBrace => Key::KpRightBrace,
        Keycode::KpTab => Key::KpTab,
        Keycode::KpBackspace => Key::KpBackspace,
        Keycode::KpA => Key::KpA,
        Keycode::KpB => Key::KpB,
        Keycode::KpC => Key::KpC,
        Keycode::KpD => Key::KpD,
        Keycode::KpE => Key::KpE,
        Keycode::KpF => Key::KpF,
        Keycode::KpXor => Key::KpXor,
        Keycode::KpPower => Key::KpPower,
        Keycode::KpPercent => Key::KpPercent,
        Keycode::KpLess => Key::KpLess,
        Keycode::KpGreater => Key::KpGreater,
        Keycode::KpAmpersand => Key::KpAmpersand,
        Keycode::KpDblAmpersand => Key::KpDblAmpersand,
        Keycode::KpVerticalBar => Key::KpVerticalBar,
        Keycode::KpDblVerticalBar => Key::KpDblVerticalBar,
        Keycode::KpColon => Key::KpColon,
        Keycode::KpHash => Key::KpHash,
        Keycode::KpSpace => Key::KpSpace,
        Keycode::KpAt => Key::KpAt,
        Keycode::KpExclam => Key::KpExclam,
        Keycode::KpMemStore => Key::KpMemStore,
        Keycode::KpMemRecall => Key::KpMemRecall,
        Keycode::KpMemClear => Key::KpMemClear,
        Keycode::KpMemAdd => Key::KpMemAdd,
        Keycode::KpMemSubtract => Key::KpMemSubtract,
        Keycode::KpMemMultiply => Key::KpMemMultiply,
        Keycode::KpMemDivide => Key::KpMemDivide,
        Keycode::KpPlusMinus => Key::KpPlusMinus,
        Keycode::KpClear => Key::KpClear,
        Keycode::KpClearEntry => Key::KpClearEntry,
        Keycode::KpBinary => Key::KpBinary,
        Keycode::KpOctal => Key::KpOctal,
        Keycode::KpDecimal => Key::KpDecimal,
        Keycode::KpHexadecimal => Key::KpHexadecimal,
        Keycode::LCtrl => Key::LCtrl,
        Keycode::LShift => Key::LShift,
        Keycode::LAlt => Key::LAlt,
        Keycode::LGui => Key::LGui,
        Keycode::RCtrl => Key::RCtrl,
        Keycode::RShift => Key::RShift,
        Keycode::RAlt => Key::RAlt,
        Keycode::RGui => Key::RGui,
        Keycode::Mode => Key::Mode,
        Keycode::AudioNext => Key::AudioNext,
        Keycode::AudioPrev => Key::AudioPrev,
        Keycode::AudioStop => Key::AudioStop,
        Keycode::AudioPlay => Key::AudioPlay,
        Keycode::AudioMute => Key::AudioMute,
        Keycode::MediaSelect => Key::MediaSelect,
        Keycode::Www => Key::Www,
        Keycode::Mail => Key::Mail,
        Keycode::Calculator => Key::Calculator,
        Keycode::Computer => Key::Computer,
        Keycode::AcSearch => Key::AcSearch,
        Keycode::AcHome => Key::AcHome,
        Keycode::AcBack => Key::AcBack,
        Keycode::AcForward => Key::AcForward,
        Keycode::AcStop => Key::AcStop,
        Keycode::AcRefresh => Key::AcRefresh,
        Keycode::AcBookmarks => Key::AcBookmarks,
        Keycode::BrightnessDown => Key::BrightnessDown,
        Keycode::BrightnessUp => Key::BrightnessUp,
        Keycode::DisplaySwitch => Key::DisplaySwitch,
        Keycode::KbdIllumToggle => Key::KbdIllumToggle,
        Keycode::KbdIllumDown => Key::KbdIllumDown,
        Keycode::KbdIllumUp => Key::KbdIllumUp,
        Keycode::Eject => Key::Eject,
        Keycode::Sleep => Key::Sleep,
    }) as usize
}

enum Key {
    Backspace,
    Tab,
    Return,
    Escape,
    Space,
    Exclaim,
    Quotedbl,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Quote,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Colon,
    Semicolon,
    Less,
    Equals,
    Greater,
    Question,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Backquote,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Delete,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    NumLockClear,
    KpDivide,
    KpMultiply,
    KpMinus,
    KpPlus,
    KpEnter,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    Kp0,
    KpPeriod,
    Application,
    Power,
    KpEquals,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    Mute,
    VolumeUp,
    VolumeDown,
    KpComma,
    KpEqualsAS400,
    AltErase,
    Sysreq,
    Cancel,
    Clear,
    Prior,
    Return2,
    Separator,
    Out,
    Oper,
    ClearAgain,
    CrSel,
    ExSel,
    Kp00,
    Kp000,
    ThousandsSeparator,
    DecimalSeparator,
    CurrencyUnit,
    CurrencySubUnit,
    KpLeftParen,
    KpRightParen,
    KpLeftBrace,
    KpRightBrace,
    KpTab,
    KpBackspace,
    KpA,
    KpB,
    KpC,
    KpD,
    KpE,
    KpF,
    KpXor,
    KpPower,
    KpPercent,
    KpLess,
    KpGreater,
    KpAmpersand,
    KpDblAmpersand,
    KpVerticalBar,
    KpDblVerticalBar,
    KpColon,
    KpHash,
    KpSpace,
    KpAt,
    KpExclam,
    KpMemStore,
    KpMemRecall,
    KpMemClear,
    KpMemAdd,
    KpMemSubtract,
    KpMemMultiply,
    KpMemDivide,
    KpPlusMinus,
    KpClear,
    KpClearEntry,
    KpBinary,
    KpOctal,
    KpDecimal,
    KpHexadecimal,
    LCtrl,
    LShift,
    LAlt,
    LGui,
    RCtrl,
    RShift,
    RAlt,
    RGui,
    Mode,
    AudioNext,
    AudioPrev,
    AudioStop,
    AudioPlay,
    AudioMute,
    MediaSelect,
    Www,
    Mail,
    Calculator,
    Computer,
    AcSearch,
    AcHome,
    AcBack,
    AcForward,
    AcStop,
    AcRefresh,
    AcBookmarks,
    BrightnessDown,
    BrightnessUp,
    DisplaySwitch,
    KbdIllumToggle,
    KbdIllumDown,
    KbdIllumUp,
    Eject,
    Sleep,
}

pub(super) const KEY_COUNT: usize = KEYS.len();

const KEYS: &[Keycode] = &[
    Keycode::Backspace,
    Keycode::Tab,
    Keycode::Return,
    Keycode::Escape,
    Keycode::Space,
    Keycode::Exclaim,
    Keycode::Quotedbl,
    Keycode::Hash,
    Keycode::Dollar,
    Keycode::Percent,
    Keycode::Ampersand,
    Keycode::Quote,
    Keycode::LeftParen,
    Keycode::RightParen,
    Keycode::Asterisk,
    Keycode::Plus,
    Keycode::Comma,
    Keycode::Minus,
    Keycode::Period,
    Keycode::Slash,
    Keycode::Num0,
    Keycode::Num1,
    Keycode::Num2,
    Keycode::Num3,
    Keycode::Num4,
    Keycode::Num5,
    Keycode::Num6,
    Keycode::Num7,
    Keycode::Num8,
    Keycode::Num9,
    Keycode::Colon,
    Keycode::Semicolon,
    Keycode::Less,
    Keycode::Equals,
    Keycode::Greater,
    Keycode::Question,
    Keycode::At,
    Keycode::LeftBracket,
    Keycode::Backslash,
    Keycode::RightBracket,
    Keycode::Caret,
    Keycode::Underscore,
    Keycode::Backquote,
    Keycode::A,
    Keycode::B,
    Keycode::C,
    Keycode::D,
    Keycode::E,
    Keycode::F,
    Keycode::G,
    Keycode::H,
    Keycode::I,
    Keycode::J,
    Keycode::K,
    Keycode::L,
    Keycode::M,
    Keycode::N,
    Keycode::O,
    Keycode::P,
    Keycode::Q,
    Keycode::R,
    Keycode::S,
    Keycode::T,
    Keycode::U,
    Keycode::V,
    Keycode::W,
    Keycode::X,
    Keycode::Y,
    Keycode::Z,
    Keycode::Delete,
    Keycode::CapsLock,
    Keycode::F1,
    Keycode::F2,
    Keycode::F3,
    Keycode::F4,
    Keycode::F5,
    Keycode::F6,
    Keycode::F7,
    Keycode::F8,
    Keycode::F9,
    Keycode::F10,
    Keycode::F11,
    Keycode::F12,
    Keycode::PrintScreen,
    Keycode::ScrollLock,
    Keycode::Pause,
    Keycode::Insert,
    Keycode::Home,
    Keycode::PageUp,
    Keycode::End,
    Keycode::PageDown,
    Keycode::Right,
    Keycode::Left,
    Keycode::Down,
    Keycode::Up,
    Keycode::NumLockClear,
    Keycode::KpDivide,
    Keycode::KpMultiply,
    Keycode::KpMinus,
    Keycode::KpPlus,
    Keycode::KpEnter,
    Keycode::Kp1,
    Keycode::Kp2,
    Keycode::Kp3,
    Keycode::Kp4,
    Keycode::Kp5,
    Keycode::Kp6,
    Keycode::Kp7,
    Keycode::Kp8,
    Keycode::Kp9,
    Keycode::Kp0,
    Keycode::KpPeriod,
    Keycode::Application,
    Keycode::Power,
    Keycode::KpEquals,
    Keycode::F13,
    Keycode::F14,
    Keycode::F15,
    Keycode::F16,
    Keycode::F17,
    Keycode::F18,
    Keycode::F19,
    Keycode::F20,
    Keycode::F21,
    Keycode::F22,
    Keycode::F23,
    Keycode::F24,
    Keycode::Execute,
    Keycode::Help,
    Keycode::Menu,
    Keycode::Select,
    Keycode::Stop,
    Keycode::Again,
    Keycode::Undo,
    Keycode::Cut,
    Keycode::Copy,
    Keycode::Paste,
    Keycode::Find,
    Keycode::Mute,
    Keycode::VolumeUp,
    Keycode::VolumeDown,
    Keycode::KpComma,
    Keycode::KpEqualsAS400,
    Keycode::AltErase,
    Keycode::Sysreq,
    Keycode::Cancel,
    Keycode::Clear,
    Keycode::Prior,
    Keycode::Return2,
    Keycode::Separator,
    Keycode::Out,
    Keycode::Oper,
    Keycode::ClearAgain,
    Keycode::CrSel,
    Keycode::ExSel,
    Keycode::Kp00,
    Keycode::Kp000,
    Keycode::ThousandsSeparator,
    Keycode::DecimalSeparator,
    Keycode::CurrencyUnit,
    Keycode::CurrencySubUnit,
    Keycode::KpLeftParen,
    Keycode::KpRightParen,
    Keycode::KpLeftBrace,
    Keycode::KpRightBrace,
    Keycode::KpTab,
    Keycode::KpBackspace,
    Keycode::KpA,
    Keycode::KpB,
    Keycode::KpC,
    Keycode::KpD,
    Keycode::KpE,
    Keycode::KpF,
    Keycode::KpXor,
    Keycode::KpPower,
    Keycode::KpPercent,
    Keycode::KpLess,
    Keycode::KpGreater,
    Keycode::KpAmpersand,
    Keycode::KpDblAmpersand,
    Keycode::KpVerticalBar,
    Keycode::KpDblVerticalBar,
    Keycode::KpColon,
    Keycode::KpHash,
    Keycode::KpSpace,
    Keycode::KpAt,
    Keycode::KpExclam,
    Keycode::KpMemStore,
    Keycode::KpMemRecall,
    Keycode::KpMemClear,
    Keycode::KpMemAdd,
    Keycode::KpMemSubtract,
    Keycode::KpMemMultiply,
    Keycode::KpMemDivide,
    Keycode::KpPlusMinus,
    Keycode::KpClear,
    Keycode::KpClearEntry,
    Keycode::KpBinary,
    Keycode::KpOctal,
    Keycode::KpDecimal,
    Keycode::KpHexadecimal,
    Keycode::LCtrl,
    Keycode::LShift,
    Keycode::LAlt,
    Keycode::LGui,
    Keycode::RCtrl,
    Keycode::RShift,
    Keycode::RAlt,
    Keycode::RGui,
    Keycode::Mode,
    Keycode::AudioNext,
    Keycode::AudioPrev,
    Keycode::AudioStop,
    Keycode::AudioPlay,
    Keycode::AudioMute,
    Keycode::MediaSelect,
    Keycode::Www,
    Keycode::Mail,
    Keycode::Calculator,
    Keycode::Computer,
    Keycode::AcSearch,
    Keycode::AcHome,
    Keycode::AcBack,
    Keycode::AcForward,
    Keycode::AcStop,
    Keycode::AcRefresh,
    Keycode::AcBookmarks,
    Keycode::BrightnessDown,
    Keycode::BrightnessUp,
    Keycode::DisplaySwitch,
    Keycode::KbdIllumToggle,
    Keycode::KbdIllumDown,
    Keycode::KbdIllumUp,
    Keycode::Eject,
    Keycode::Sleep,
];
